import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(scriptDir, '..')

const file = relativePath =>
  path.join(rootDir, relativePath)

const packageJson = JSON.parse(
  await fs.readFile(
    file('package.json'),
    'utf8'
  )
)

const version = String(packageJson.version || '').trim()

if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(
    `package.json version không hợp lệ: "${version}"`
  )
}

const appMeta = `/* =========================================================
   CHEMLAB RELEASE METADATA

   This file is generated by scripts/sync-release.mjs.
   Change the release version in package.json, then run:
   npm run release:sync
========================================================= */

export const APP_META = Object.freeze({
  name: 'ChemLab',
  edition: 'Huu Nghia Edition',
  version: '${version}',
  author: 'Huu Nghia',
  release: 'Production',
  description: 'Interactive Chemistry Workspace'
})

export const APP_VERSION = APP_META.version
`

await fs.writeFile(
  file('src/appMeta.js'),
  appMeta,
  'utf8'
)

const indexPath = file('index.html')
let indexHtml = await fs.readFile(indexPath, 'utf8')

indexHtml = indexHtml
  .replace(
    /ChemLab \d+\.\d+(?:\.\d+)?/g,
    `ChemLab ${version}`
  )
  .replace(
    /Hữu Nghĩa Edition\s*•\s*\d+\.\d+(?:\.\d+)?/g,
    `Hữu Nghĩa Edition • ${version}`
  )
  .replace(
    /ChemLab [^|<\n]+\| Huu Nghiaaa/g,
    `ChemLab ${version} | Huu Nghia`
  )

await fs.writeFile(
  indexPath,
  indexHtml,
  'utf8'
)

const manifestPath = file('public/manifest.webmanifest')
const manifest = JSON.parse(
  await fs.readFile(manifestPath, 'utf8')
)

manifest.name =
  `ChemLab ${version} — Hữu Nghĩa Edition`

await fs.writeFile(
  manifestPath,
  `${JSON.stringify(manifest, null, 2)}\n`,
  'utf8'
)

const serviceWorkerPath = file('public/sw.js')
let serviceWorker = await fs.readFile(serviceWorkerPath, 'utf8')

serviceWorker = serviceWorker
  .replace(
    /CHEMLAB \d+\.\d+(?:\.\d+)?/,
    `CHEMLAB ${version}`
  )
  .replace(
    /'chemlab-\d+\.\d+(?:\.\d+)?'/,
    `'chemlab-${version}'`
  )

await fs.writeFile(
  serviceWorkerPath,
  serviceWorker,
  'utf8'
)

console.log(
  `[ChemLab] Release metadata synced to ${version}.`
)
