/* =========================================================
   CHEMLAB RELEASE METADATA

   This file is generated by scripts/sync-release.mjs.
   Change the release version in package.json, then run:
   npm run release:sync
========================================================= */

export const APP_META = Object.freeze({
  name: 'ChemLab',
  edition: 'Huu Nghia Edition',
  version: '6.2.0',
  author: 'Huu Nghia',
  release: 'Production',
  description: 'Interactive Chemistry Workspace'
})

export const APP_VERSION = APP_META.version
